databases:
  - name: render_com_db
    databaseName: myapp_production
    user: myapp
    region: singapore

services:
  - type: web
    name: TheatreTicketAlbum
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: render_com_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false